spring:
  profiles:
    active: dev
    group:
      local-env:
        - local
      dev-env:
        - dev
    include:
      - jwt
      - s3
      - openai
#      - oauth
logging:
  level:
    org:
      springframework:
        security=DEBUG: